spring.datasource.url=jdbc:postgresql://ep-bold-firefly-ai1lvqhp-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_1ejI0TlbEDMo
spring.datasource.driver-class-name=org.postgresql.Driver
